### ISSUE TITLE
Script don't work 

### ISSUE THREAD

**Issue by alexieze** [ElusiveMind/osx_server_enhancements#4]
Hi! Use your script no longer works as it is possible to return anything change? Gd library was deleted, Intl, mycrypt and other not install. Thank you.

**Comment by ElusiveMind** [comment]
Did you install Command Line Tools?

**Comment by ElusiveMind** [comment]
Install this:

https://www.dropbox.com/s/zmp557wfc2ovne8/Command_Line_Tools_OS_X_10.10_for_Xcode_6.4.dmg?dl=0

And try again

**Comment by alexieze** [comment]
Hi! Command Line Tools was installed. Thank you for your help, I installed php with Free Type and support PNG.

**Comment by ElusiveMind** [comment]
Yes... unfortunately even with Xcode installed, the command line tools will be required to use this package. I am updating the documentation tonight. I have tried and run into numerous prerequisites that Apple includes on their internal build that they do not provide with Xcode, only the Command Line Tools. Very odd.
