### ISSUE TITLE
Suggested updates to the documentation

### ISSUE THREAD

**Issue by ganar** [ElusiveMind/osx_server_enhancements#5]
There are a number of clarifications that may go in to the documentation

### Please add the instructions to restart from the restore image:

* **On a normal machine:** Reboot the Mac and hold down Command + R keys simultaneously after you hear the startup chime, this will boot OS X into Recovery Mode (you can also [link to this excellent article on the subject](http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/)
* **On a Hackintosh:** Reboot the Mac and enter into recovery mode from the *Clover* menu

### for the noobs (like me): instructions on how to run the installer

* `cd` to the directory where the `php-enhancer.sh` is located
* Drag and drop the file `php-enhancer.sh` in the terminal, hit return

### Please specify what to do with the files left in the directory after the installation

* Should the user keep this files? can they be erased without consequence?

Thanks a lot for your efforts: this work is quite helpful

**Comment by ElusiveMind** [comment]
I'm going to be completely revamping documentation based on the revamped process and bash install script today.

**Comment by ganar** [comment]
Thanks, Michael
